import type {
  ConsoleSnapshot,
  Provider,
  Model,
  ModelMapping,
  RequestLog,
  RuntimeConfig,
  Settings,
} from "./types"

export const initialProviders: Provider[] = [
  {
    id: "prov-openai",
    name: "OpenAI 官方",
    protocol: "openai-responses",
    baseUrl: "https://api.openai.com/v1",
    apiKey: "sk-REPLACE_WITH_OPENAI_KEY",
    headers: [{ id: "h1", key: "OpenAI-Beta", value: "responses-2025" }],
    bodyOverride: "",
    timeoutMs: 60000,
    reasoningDialect: "openai-reasoning-effort",
    rawResponsesPassthrough: false,
    enabled: true,
    isDefault: true,
    health: "healthy",
  },
  {
    id: "prov-anthropic",
    name: "Anthropic Claude",
    protocol: "anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    apiKey: "sk-ant-REPLACE_WITH_ANTHROPIC_KEY",
    headers: [{ id: "h2", key: "anthropic-version", value: "2023-06-01" }],
    bodyOverride: "",
    timeoutMs: 90000,
    reasoningDialect: "none",
    rawResponsesPassthrough: false,
    enabled: true,
    isDefault: false,
    health: "healthy",
  },
  {
    id: "prov-deepseek",
    name: "DeepSeek 中转",
    protocol: "openai-chat",
    baseUrl: "https://api.deepseek.com/v1",
    apiKey: "sk-REPLACE_WITH_DEEPSEEK_KEY",
    headers: [],
    bodyOverride: "",
    timeoutMs: 120000,
    reasoningDialect: "deepseek-official",
    rawResponsesPassthrough: false,
    enabled: true,
    isDefault: false,
    health: "degraded",
    healthMessage: "最近 5 分钟错误率 12%，上游延迟偏高",
  },
  {
    id: "prov-local",
    name: "本地 vLLM",
    protocol: "openai-chat",
    baseUrl: "http://192.168.1.20:8000/v1",
    apiKey: "local-none",
    headers: [{ id: "h3", key: "X-Cluster", value: "gpu-node-1" }],
    bodyOverride: "",
    timeoutMs: 30000,
    reasoningDialect: "qwen-enable-thinking",
    rawResponsesPassthrough: false,
    enabled: false,
    isDefault: false,
    health: "down",
    healthMessage: "连接被拒绝：dial tcp 192.168.1.20:8000: connect: connection refused",
  },
]

export const initialModels: Model[] = [
  {
    id: "m-gpt-image-2",
    providerId: "prov-openai",
    displayName: "GPT Image 2",
    modelId: "gpt-image-2",
    capabilities: ["image_generation"],
    contextLength: 0,
    supportsReasoning: false,
    reasoningDialect: "inherit",
    supportsVision: false,
    enabled: true,
  },
  {
    id: "m-gpt55",
    providerId: "prov-openai",
    displayName: "GPT-5.5",
    modelId: "gpt-5.5",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: true,
    enabled: true,
  },
  {
    id: "m-gpt54",
    providerId: "prov-openai",
    displayName: "GPT-5.4",
    modelId: "gpt-5.4",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: true,
    enabled: true,
  },
  {
    id: "m-gpt54-mini",
    providerId: "prov-openai",
    displayName: "GPT-5.4-Mini",
    modelId: "gpt-5.4-mini",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 128000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: true,
    enabled: true,
  },
  {
    id: "m-gpt54-nano",
    providerId: "prov-openai",
    displayName: "GPT-5.4 Nano",
    modelId: "gpt-5.4-nano",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: true,
    enabled: true,
  },
  {
    id: "m-gpt53-codex",
    providerId: "prov-openai",
    displayName: "GPT-5.3-Codex",
    modelId: "gpt-5.3-codex",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: true,
    enabled: true,
  },
  {
    id: "m-gpt52",
    providerId: "prov-openai",
    displayName: "GPT-5.2",
    modelId: "gpt-5.2",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: true,
    enabled: true,
  },
  {
    id: "m-gpt5",
    providerId: "prov-openai",
    displayName: "GPT-5",
    modelId: "gpt-5",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: true,
    enabled: true,
  },
  {
    id: "m-gpt5-mini",
    providerId: "prov-openai",
    displayName: "GPT-5 Mini",
    modelId: "gpt-5-mini",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: true,
    enabled: true,
  },
  {
    id: "m-gpt5-nano",
    providerId: "prov-openai",
    displayName: "GPT-5 Nano",
    modelId: "gpt-5-nano",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: true,
    enabled: true,
  },
  {
    id: "m-claude-opus",
    providerId: "prov-anthropic",
    displayName: "Claude Opus 4.8",
    modelId: "claude-opus-4-8",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 400000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: true,
    enabled: true,
  },
  {
    id: "m-claude-sonnet",
    providerId: "prov-anthropic",
    displayName: "Claude Sonnet 4.6",
    modelId: "claude-sonnet-4-6",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 400000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: true,
    enabled: true,
  },
  {
    id: "m-claude-haiku",
    providerId: "prov-anthropic",
    displayName: "Claude Haiku 4.5",
    modelId: "claude-haiku-4-5-20251001",
    capabilities: ["chat", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: false,
    reasoningDialect: "inherit",
    supportsVision: true,
    enabled: true,
  },
  {
    id: "m-deepseek-v4-pro",
    providerId: "prov-deepseek",
    displayName: "DeepSeek V4 Pro",
    modelId: "deepseek-v4-pro",
    capabilities: ["chat", "reasoning", "tools"],
    contextLength: 1000000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: false,
    enabled: true,
  },
  {
    id: "m-deepseek-v4-flash",
    providerId: "prov-deepseek",
    displayName: "DeepSeek V4 Flash",
    modelId: "deepseek-v4-flash",
    capabilities: ["chat", "reasoning", "tools"],
    contextLength: 1000000,
    supportsReasoning: true,
    reasoningDialect: "inherit",
    supportsVision: false,
    enabled: true,
  },
  {
    id: "m-local-qwen",
    providerId: "prov-local",
    displayName: "Qwen3 32B (本地)",
    modelId: "qwen3-32b",
    capabilities: ["chat", "tools"],
    contextLength: 32000,
    supportsReasoning: false,
    reasoningDialect: "inherit",
    supportsVision: false,
    enabled: false,
  },
]

export const initialMappings: ModelMapping[] = []

export const initialRuntime: RuntimeConfig = {
  takeover: "active",
  activeProviderId: "prov-openai",
  activeModelId: "m-gpt5",
  reasoning: "auto",
}

export const initialSettings: Settings = {
  listenAddress: "127.0.0.1",
  port: 8787,
  takeoverEnabled: true,
  defaultProviderId: "prov-openai",
  defaultModelId: "m-gpt5",
  defaultReasoning: "auto",
  auxiliaryRoutingEnabled: false,
  auxiliaryProviderId: "prov-openai",
  auxiliaryModelId: "m-gpt54-mini",
  auxiliaryReasoning: "low",
  imageGenerationProviderId: "prov-openai",
  imageGenerationModelId: "m-gpt-image-2",
  logRetentionDays: 14,
  fullRequestLoggingEnabled: false,
  webSearchMode: "builtin",
  keyStorage: "系统钥匙串（占位）",
  floatingBallEnabled: true,
  tokenStatsResetAt: "1970-01-01T00:00:00.000Z",
}

function ts(minutesAgo: number): string {
  return new Date(Date.now() - minutesAgo * 60000).toISOString()
}

export const sampleLogs: RequestLog[] = [
  {
    id: "log-1",
    timestamp: ts(1),
    codexModel: "switchgate__auto",
    finalProviderId: "prov-anthropic",
    finalModelId: "claude-opus-4-8",
    reasoning: "high",
    statusCode: 200,
    durationMs: 2340,
    tokenUsage: {
      inputTokens: 18240,
      outputTokens: 612,
      totalTokens: 18852,
      cachedInputTokens: 4096,
      cacheCreationInputTokens: 0,
    },
    rawRequest: 'POST /v1/responses\nmodel: "switchgate__auto"\nreasoning: { effort: "medium" }\nmessages: 4 条',
    rewrittenRequest:
      'POST https://api.anthropic.com/v1/messages\nmodel: "claude-opus-4-8"\nthinking: { type: "adaptive" }\noutput_config: { effort: "high" }\nmessages: 4 条（已转换为 Anthropic 格式）',
    responseSummary: "200 OK · 输出 612 tokens · stop_reason: end_turn",
  },
  {
    id: "log-2",
    timestamp: ts(3),
    codexModel: "gpt-4o",
    finalProviderId: "prov-deepseek",
    finalModelId: "deepseek-v4-flash",
    reasoning: "off",
    statusCode: 200,
    durationMs: 1180,
    tokenUsage: {
      inputTokens: 1680,
      outputTokens: 245,
      totalTokens: 1925,
    },
    rawRequest: 'POST /v1/chat/completions\nmodel: "gpt-4o"\nmessages: 2 条',
    rewrittenRequest: 'POST https://api.deepseek.com/v1/chat/completions\nmodel: "deepseek-v4-flash"\nmessages: 2 条',
    responseSummary: "200 OK · 输出 245 tokens · finish_reason: stop",
  },
  {
    id: "log-3",
    timestamp: ts(6),
    codexModel: "o3-mini",
    finalProviderId: "prov-deepseek",
    finalModelId: "deepseek-v4-pro",
    reasoning: "medium",
    statusCode: 429,
    durationMs: 890,
    error: "上游返回 429：Rate limit exceeded（每分钟请求数超限）",
    rawRequest: 'POST /v1/chat/completions\nmodel: "o3-mini"\nreasoning: { effort: "high" }',
    rewrittenRequest: 'POST https://api.deepseek.com/v1/chat/completions\nmodel: "deepseek-v4-pro"',
    responseSummary: "429 Too Many Requests",
    errorStack:
      'RateLimitError: Rate limit exceeded\n    at DeepSeekClient.post (proxy/clients/deepseek.ts:88:13)\n    at async RewritePipeline.forward (proxy/pipeline.ts:142:20)\n    at async handleRequest (proxy/server.ts:64:11)\nupstream_headers: { "retry-after": "12" }',
  },
  {
    id: "log-4",
    timestamp: ts(9),
    codexModel: "switchgate__auto",
    finalProviderId: "prov-anthropic",
    finalModelId: "claude-opus-4-8",
    reasoning: "high",
    statusCode: 200,
    durationMs: 3010,
    tokenUsage: {
      inputTokens: 24960,
      outputTokens: 1024,
      totalTokens: 25984,
      cachedInputTokens: 8192,
      reasoningTokens: 128,
    },
    rawRequest: 'POST /v1/responses\nmodel: "switchgate__auto"\nreasoning: { effort: "low" }',
    rewrittenRequest:
      'POST https://api.anthropic.com/v1/messages\nmodel: "claude-opus-4-8"\nthinking: { type: "adaptive" }\noutput_config: { effort: "high" }',
    responseSummary: "200 OK · 输出 1024 tokens · stop_reason: end_turn",
  },
  {
    id: "log-5",
    timestamp: ts(12),
    codexModel: "gpt-4o-mini",
    finalProviderId: "prov-local",
    finalModelId: "qwen3-32b",
    reasoning: "off",
    statusCode: 502,
    durationMs: 30021,
    error: "连接本地供应商失败：connection refused（端口 8000 无响应）",
    rawRequest: 'POST /v1/chat/completions\nmodel: "gpt-4o-mini"',
    rewrittenRequest: 'POST http://192.168.1.20:8000/v1/chat/completions\nmodel: "qwen3-32b"',
    responseSummary: "502 Bad Gateway（超时 30000ms）",
    errorStack:
      'FetchError: request to http://192.168.1.20:8000/v1/chat/completions failed\n    code: ECONNREFUSED\n    at ClientRequest.<anonymous> (proxy/clients/openai.ts:54:19)\n    at async RewritePipeline.forward (proxy/pipeline.ts:142:20)',
  },
  {
    id: "log-6",
    timestamp: ts(15),
    codexModel: "switchgate__auto",
    finalProviderId: "prov-anthropic",
    finalModelId: "claude-opus-4-8",
    reasoning: "medium",
    statusCode: 200,
    durationMs: 1980,
    rawRequest: 'POST /v1/responses\nmodel: "switchgate__auto"',
    rewrittenRequest: 'POST https://api.anthropic.com/v1/messages\nmodel: "claude-opus-4-8"',
    responseSummary: "200 OK · 输出 388 tokens",
  },
]

export const initialSnapshot: ConsoleSnapshot = {
  version: 1,
  providers: initialProviders,
  models: initialModels,
  mappings: initialMappings,
  logs: [],
  tokenStats: [],
  runtime: initialRuntime,
  settings: initialSettings,
}
