import type {
  Model,
  ModelReasoningDialect,
  Provider,
  ProtocolType,
  ReasoningDialect,
} from "@/lib/types"

export interface ProviderPresetModel {
  displayName: string
  modelId: string
  capabilities: string[]
  contextLength: number
  supportsReasoning: boolean
  reasoningDialect?: ModelReasoningDialect
  supportsVision: boolean
}

export interface ProviderPreset {
  id: string
  name: string
  category: "国内" | "海外" | "聚合"
  protocol: ProtocolType
  baseUrl: string
  timeoutMs: number
  reasoningDialect: ReasoningDialect
  headers?: Array<{ key: string; value: string }>
  apiKeyPlaceholder: string
  note: string
  deprecatedModelIds?: string[]
  replacementModelIds?: Record<string, string>
  models: ProviderPresetModel[]
}

export interface ProviderPresetDraft {
  provider: Provider
  models: Model[]
}

const CLAUDE_PRESET_MODELS: ProviderPresetModel[] = [
  {
    displayName: "Claude Fable 5",
    modelId: "claude-fable-5",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    supportsVision: true,
  },
  {
    displayName: "Claude Sonnet 5",
    modelId: "claude-sonnet-5",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 400000,
    supportsReasoning: true,
    supportsVision: true,
  },
  {
    displayName: "Claude Opus 4.8",
    modelId: "claude-opus-4-8",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 400000,
    supportsReasoning: true,
    supportsVision: true,
  },
  {
    displayName: "Claude Sonnet 4.6",
    modelId: "claude-sonnet-4-6",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 400000,
    supportsReasoning: true,
    supportsVision: true,
  },
  {
    displayName: "Claude Haiku 4.5",
    modelId: "claude-haiku-4-5-20251001",
    capabilities: ["chat", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: false,
    supportsVision: true,
  },
]

const CLAUDE_DEPRECATED_MODEL_IDS = [
  "claude-mythos-5",
  "claude-opus-4-6",
  "claude-opus-4-7",
]

const CLAUDE_REPLACEMENT_MODEL_IDS = {
  "claude-mythos-5": "claude-opus-4-8",
  "claude-opus-4-6": "claude-opus-4-8",
  "claude-opus-4-7": "claude-opus-4-8",
}

const OPENAI_CODEX_PRESET_MODELS: ProviderPresetModel[] = [
  {
    displayName: "GPT-5.5",
    modelId: "gpt-5.5",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    supportsVision: true,
  },
  {
    displayName: "GPT-5.4",
    modelId: "gpt-5.4",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    supportsVision: true,
  },
  {
    displayName: "GPT-5.4 Mini",
    modelId: "gpt-5.4-mini",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 128000,
    supportsReasoning: true,
    supportsVision: true,
  },
  {
    displayName: "GPT-5.3 Codex",
    modelId: "gpt-5.3-codex",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    supportsVision: true,
  },
  {
    displayName: "GPT-5.2",
    modelId: "gpt-5.2",
    capabilities: ["chat", "reasoning", "vision", "tools"],
    contextLength: 272000,
    supportsReasoning: true,
    supportsVision: true,
  },
]

const OPENAI_COMPATIBLE_PRESET_MODELS: ProviderPresetModel[] = [
  {
    displayName: "GPT Image 2",
    modelId: "gpt-image-2",
    capabilities: ["image_generation"],
    contextLength: 0,
    supportsReasoning: false,
    supportsVision: false,
  },
  ...OPENAI_CODEX_PRESET_MODELS,
]

const OPENAI_OFFICIAL_PRESET_MODELS: ProviderPresetModel[] = [
  {
    displayName: "GPT Image 2",
    modelId: "gpt-image-2",
    capabilities: ["image_generation"],
    contextLength: 0,
    supportsReasoning: false,
    supportsVision: false,
  },
  ...OPENAI_CODEX_PRESET_MODELS,
]

export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    id: "sharesai-relay",
    name: "SharesAI / 白白中转",
    category: "聚合",
    protocol: "openai-responses",
    baseUrl: "https://api.sharesai.xyz/v1",
    timeoutMs: 600000,
    reasoningDialect: "openai-reasoning-effort",
    apiKeyPlaceholder: "SharesAI API Key",
    note: "SharesAI Codex/OpenAI Responses 兼容中转，已在上游完成协议适配；本项目只做热切换、模型选择、日志和必要的流式修复。",
    models: OPENAI_COMPATIBLE_PRESET_MODELS,
  },
  {
    id: "openai-official",
    name: "OpenAI 官方",
    category: "海外",
    protocol: "openai-responses",
    baseUrl: "https://api.openai.com/v1",
    timeoutMs: 60000,
    reasoningDialect: "openai-reasoning-effort",
    apiKeyPlaceholder: "sk-...",
    note: "OpenAI 官方 Responses 入口，适合作为 Codex 默认接管出口；预设 GPT Image 2 和 Codex 当前模型下拉里的五个模型。",
    models: OPENAI_OFFICIAL_PRESET_MODELS,
  },
  {
    id: "anthropic-official",
    name: "Anthropic Claude 官方",
    category: "海外",
    protocol: "anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    timeoutMs: 600000,
    reasoningDialect: "none",
    apiKeyPlaceholder: "sk-ant-...",
    note: "Anthropic Messages 原生协议入口；本地中转会把 Codex/OpenAI Responses 与 Chat 请求转换成 Claude Messages。Fable/Mythos 5 访问已暂停，默认迁移到 Opus 4.8。",
    deprecatedModelIds: CLAUDE_DEPRECATED_MODEL_IDS,
    replacementModelIds: CLAUDE_REPLACEMENT_MODEL_IDS,
    models: CLAUDE_PRESET_MODELS,
  },
  {
    id: "auth2api-claude-oauth",
    name: "auth2api Claude OAuth",
    category: "海外",
    protocol: "openai-responses",
    baseUrl: "http://127.0.0.1:8317/v1",
    timeoutMs: 600000,
    reasoningDialect: "openai-reasoning-effort",
    apiKeyPlaceholder: "auth2api 配置的 api-key",
    note: "auth2api 本地 OAuth 网关，Claude 订阅账号登录后可用；它同时支持 /v1/responses、/v1/chat/completions 和 /v1/messages。",
    deprecatedModelIds: CLAUDE_DEPRECATED_MODEL_IDS,
    replacementModelIds: CLAUDE_REPLACEMENT_MODEL_IDS,
    models: CLAUDE_PRESET_MODELS,
  },
  {
    id: "cliproxyapi-claude-oauth",
    name: "CLIProxyAPI Claude OAuth",
    category: "聚合",
    protocol: "openai-responses",
    baseUrl: "http://127.0.0.1:8317",
    timeoutMs: 600000,
    reasoningDialect: "openai-reasoning-effort",
    apiKeyPlaceholder: "CLIProxyAPI 管理密钥或任意本地 key",
    note: "CLIProxyAPI 本地多账号网关，默认端口 8317；适合把 Claude Code OAuth、多账号轮询和本项目热切换串起来。",
    deprecatedModelIds: CLAUDE_DEPRECATED_MODEL_IDS,
    replacementModelIds: CLAUDE_REPLACEMENT_MODEL_IDS,
    models: CLAUDE_PRESET_MODELS,
  },
  {
    id: "ccproxy-claude-sdk",
    name: "CCProxy Claude SDK",
    category: "聚合",
    protocol: "openai-responses",
    baseUrl: "http://127.0.0.1:8000/claude/sdk/v1",
    timeoutMs: 600000,
    reasoningDialect: "openai-reasoning-effort",
    apiKeyPlaceholder: "sk-dummy",
    note: "CCProxy Claude Code SDK 插件入口，复用本机 Claude Code 登录与 MCP 环境；如使用 Claude API 插件，可把 Base URL 改为 /claude/v1。",
    deprecatedModelIds: CLAUDE_DEPRECATED_MODEL_IDS,
    replacementModelIds: CLAUDE_REPLACEMENT_MODEL_IDS,
    models: CLAUDE_PRESET_MODELS,
  },
  {
    id: "ccproxy-claude-api",
    name: "CCProxy Claude API",
    category: "聚合",
    protocol: "openai-responses",
    baseUrl: "http://127.0.0.1:8000/claude/v1",
    timeoutMs: 600000,
    reasoningDialect: "openai-reasoning-effort",
    apiKeyPlaceholder: "sk-dummy",
    note: "CCProxy Claude API 插件入口，提供 OpenAI Chat/Responses 到 Claude 的适配；更偏向 OAuth 后直连 Anthropic API。",
    deprecatedModelIds: CLAUDE_DEPRECATED_MODEL_IDS,
    replacementModelIds: CLAUDE_REPLACEMENT_MODEL_IDS,
    models: CLAUDE_PRESET_MODELS,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    category: "国内",
    protocol: "openai-chat",
    baseUrl: "https://api.deepseek.com/v1",
    timeoutMs: 120000,
    reasoningDialect: "deepseek-official",
    apiKeyPlaceholder: "sk-...",
    note: "DeepSeek 官方 OpenAI Chat Completions 兼容入口，V4 已取代 deepseek-chat/deepseek-reasoner 旧别名。",
    deprecatedModelIds: ["deepseek-chat", "deepseek-reasoner"],
    replacementModelIds: {
      "deepseek-reasoner": "deepseek-v4-pro",
      "deepseek-chat": "deepseek-v4-flash",
    },
    models: [
      {
        displayName: "DeepSeek V4 Pro",
        modelId: "deepseek-v4-pro",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 1000000,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "DeepSeek V4 Flash",
        modelId: "deepseek-v4-flash",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 1000000,
        supportsReasoning: true,
        supportsVision: false,
      },
    ],
  },
  {
    id: "qwen-bailian",
    name: "阿里百炼 Qwen",
    category: "国内",
    protocol: "openai-responses",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    timeoutMs: 120000,
    reasoningDialect: "qwen-enable-thinking",
    apiKeyPlaceholder: "sk-...",
    note: "DashScope compatible-mode 原生支持 OpenAI Responses API；Qwen 3.6/3.7 多模态推理模型直连 /responses，避免 Responses→Chat 转换链路。",
    deprecatedModelIds: [
      "qwen-plus",
      "qwen3-max",
      "qwen3.5-plus",
      "qwen3-turbo",
      "qwen3-coder-plus",
      "qwen3.6-flash",
    ],
    replacementModelIds: {
      "qwen-plus": "qwen3.7-plus",
      "qwen3-max": "qwen3.7-max",
      "qwen3.5-plus": "qwen3.7-plus",
      "qwen3-turbo": "qwen3.6-plus",
      "qwen3-coder-plus": "qwen3.7-plus",
      "qwen3.6-flash": "qwen3.6-plus",
    },
    models: [
      {
        displayName: "Qwen3.7 Max",
        modelId: "qwen3.7-max",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 1000000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "Qwen3.7 Plus",
        modelId: "qwen3.7-plus",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 1000000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "Qwen3.6 Plus",
        modelId: "qwen3.6-plus",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 1000000,
        supportsReasoning: true,
        supportsVision: true,
      },
    ],
  },
  {
    id: "kimi",
    name: "Kimi / Moonshot",
    category: "国内",
    protocol: "openai-chat",
    baseUrl: "https://api.moonshot.cn/v1",
    timeoutMs: 120000,
    reasoningDialect: "kimi-thinking",
    apiKeyPlaceholder: "sk-...",
    note: "Moonshot OpenAI-compatible 接口，Kimi K2.6 支持原生多模态与 thinking 开关；按 CC Switch 的 Codex 预设使用 moonshot.cn 入口。",
    deprecatedModelIds: ["kimi-k2-0711-preview", "kimi-k2-0905-preview", "kimi-k2-turbo-preview"],
    replacementModelIds: {
      "kimi-k2-0711-preview": "kimi-k2.6",
      "kimi-k2-0905-preview": "kimi-k2.6",
      "kimi-k2-turbo-preview": "kimi-k2.6",
    },
    models: [
      {
        displayName: "Kimi K2.6",
        modelId: "kimi-k2.6",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 262000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "Kimi K2.5",
        modelId: "kimi-k2.5",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 262000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "Moonshot V1 128K",
        modelId: "moonshot-v1-128k",
        capabilities: ["chat", "tools"],
        contextLength: 128000,
        supportsReasoning: false,
        supportsVision: false,
      },
    ],
  },
  {
    id: "zhipu-glm",
    name: "智谱 GLM",
    category: "国内",
    protocol: "openai-chat",
    baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
    timeoutMs: 120000,
    reasoningDialect: "glm-thinking",
    apiKeyPlaceholder: "sk-...",
    note: "智谱 Codex/Coding OpenAI-compatible 入口，GLM 推理开关会映射到 thinking。",
    deprecatedModelIds: ["glm-4.6", "glm-4.5"],
    replacementModelIds: {
      "glm-4.6": "glm-5.1",
      "glm-4.5": "glm-5-turbo",
    },
    models: [
      {
        displayName: "GLM-5.1",
        modelId: "glm-5.1",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 200000,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "GLM-5 Turbo",
        modelId: "glm-5-turbo",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 200000,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "GLM-5",
        modelId: "glm-5",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 200000,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "GLM-4.7",
        modelId: "glm-4.7",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 200000,
        supportsReasoning: true,
        supportsVision: false,
      },
    ],
  },
  {
    id: "siliconflow",
    name: "硅基流动 SiliconFlow",
    category: "国内",
    protocol: "openai-chat",
    baseUrl: "https://api.siliconflow.cn/v1",
    timeoutMs: 120000,
    reasoningDialect: "siliconflow-enable-thinking",
    apiKeyPlaceholder: "sk-...",
    note: "聚合国内外开源/闭源模型，推理开关默认按硅基流动 enable_thinking 适配。",
    deprecatedModelIds: ["deepseek-ai/deepseek-r1"],
    replacementModelIds: {
      "deepseek-ai/deepseek-r1": "deepseek-ai/DeepSeek-V4-Pro",
    },
    models: [
      {
        displayName: "MiniMax M3",
        modelId: "MiniMaxAI/MiniMax-M3",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 1049000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "DeepSeek V4 Pro",
        modelId: "deepseek-ai/DeepSeek-V4-Pro",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 1049000,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "DeepSeek V4 Flash",
        modelId: "deepseek-ai/DeepSeek-V4-Flash",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 1049000,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "Kimi K2.6",
        modelId: "moonshotai/Kimi-K2.6",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 262000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "GLM-5.1",
        modelId: "zai-org/GLM-5.1",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 205000,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "Qwen3.5 397B A17B",
        modelId: "Qwen/Qwen3.5-397B-A17B",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 262000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "Qwen3 Coder 480B",
        modelId: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
        capabilities: ["chat", "tools"],
        contextLength: 262000,
        supportsReasoning: false,
        supportsVision: false,
      },
    ],
  },
  {
    id: "volcengine-ark",
    name: "火山方舟 Ark",
    category: "国内",
    protocol: "openai-chat",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    timeoutMs: 120000,
    reasoningDialect: "volcengine-thinking",
    apiKeyPlaceholder: "Bearer token",
    note: "火山方舟 OpenAI-compatible 入口，Seed 2.0 可直接使用模型 ID；自定义服务仍可填 ep- 开头 endpoint。",
    deprecatedModelIds: ["doubao-seed-1-6", "doubao-seed-1-6-flash-250615"],
    replacementModelIds: {
      "doubao-seed-1-6": "doubao-seed-2-0-pro-260215",
      "doubao-seed-1-6-flash-250615": "doubao-seed-2-0-lite-260215",
    },
    models: [
      {
        displayName: "Doubao Seed 2.0 Pro",
        modelId: "doubao-seed-2-0-pro-260215",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 256000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "Doubao Seed 2.0 Lite",
        modelId: "doubao-seed-2-0-lite-260215",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 256000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "Doubao Seed 2.0 Mini",
        modelId: "doubao-seed-2-0-mini-260215",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 256000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "Doubao Seed 2.0 Code Latest",
        modelId: "doubao-seed-2-0-code-preview-latest",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 256000,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "Doubao Seed 2.0 Code",
        modelId: "doubao-seed-2-0-code-preview-260215",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 256000,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "方舟自定义 Endpoint",
        modelId: "ep-REPLACE_WITH_ENDPOINT_ID",
        capabilities: ["chat", "tools"],
        contextLength: 128000,
        supportsReasoning: false,
        supportsVision: false,
      },
    ],
  },
  {
    id: "minimax",
    name: "MiniMax",
    category: "国内",
    protocol: "openai-chat",
    baseUrl: "https://api.minimax.io/v1",
    timeoutMs: 120000,
    reasoningDialect: "minimax-reasoning-split",
    apiKeyPlaceholder: "sk-...",
    note: "MiniMax OpenAI-compatible 入口，推理开关会映射到 reasoning_split。",
    deprecatedModelIds: ["minimax-text-01", "minimax-m1"],
    replacementModelIds: {
      "minimax-text-01": "MiniMax-M3",
      "minimax-m1": "MiniMax-M2.7",
    },
    models: [
      {
        displayName: "MiniMax M3",
        modelId: "MiniMax-M3",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 1000000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "MiniMax M2.7",
        modelId: "MiniMax-M2.7",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 204800,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "MiniMax M2.7 Highspeed",
        modelId: "MiniMax-M2.7-highspeed",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 204800,
        supportsReasoning: true,
        supportsVision: false,
      },
    ],
  },
  {
    id: "stepfun",
    name: "阶跃星辰 StepFun",
    category: "国内",
    protocol: "openai-chat",
    baseUrl: "https://api.stepfun.com/step_plan/v1",
    timeoutMs: 120000,
    reasoningDialect: "stepfun-low-high",
    apiKeyPlaceholder: "sk-...",
    note: "StepFun OpenAI-compatible 入口，推理档位会归一到 low/medium/high。",
    deprecatedModelIds: ["step-3", "step-2-16k"],
    replacementModelIds: {
      "step-3": "step-3.7-flash",
      "step-2-16k": "step-3.5-flash",
    },
    models: [
      {
        displayName: "Step 3.7 Flash",
        modelId: "step-3.7-flash",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 256000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "Step 3.5 Flash",
        modelId: "step-3.5-flash",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 256000,
        supportsReasoning: true,
        supportsVision: false,
      },
    ],
  },
  {
    id: "baidu-qianfan",
    name: "百度千帆",
    category: "国内",
    protocol: "openai-chat",
    baseUrl: "https://qianfan.baidubce.com/v2/coding",
    timeoutMs: 120000,
    reasoningDialect: "none",
    apiKeyPlaceholder: "Bearer token",
    note: "千帆 Coding Plan OpenAI-compatible 入口；深度思考主要由模型 ID 决定，默认不额外注入非标准推理参数。",
    deprecatedModelIds: ["ernie-x1-32k", "ernie-5.0-thinking-latest", "ernie-x1.1"],
    replacementModelIds: {
      "ernie-x1-32k": "ernie-x1.1-preview",
      "ernie-5.0-thinking-latest": "ernie-5.0-thinking-preview",
      "ernie-x1.1": "ernie-x1.1-preview",
    },
    models: [
      {
        displayName: "Qianfan Code Latest",
        modelId: "qianfan-code-latest",
        capabilities: ["chat", "tools"],
        contextLength: 131072,
        supportsReasoning: false,
        supportsVision: false,
      },
      {
        displayName: "ERNIE 5.1",
        modelId: "ernie-5.1",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 128000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "ERNIE 5.0 Thinking Preview",
        modelId: "ernie-5.0-thinking-preview",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 128000,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "ERNIE X1.1 Preview",
        modelId: "ernie-x1.1-preview",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 64000,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "DeepSeek V4 Pro",
        modelId: "deepseek-v4-pro",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 1155072,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "DeepSeek V4 Flash",
        modelId: "deepseek-v4-flash",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 1155072,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "DeepSeek V3.2",
        modelId: "deepseek-v3.2",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 131000,
        supportsReasoning: true,
        supportsVision: false,
      },
    ],
  },
  {
    id: "tencent-hunyuan",
    name: "腾讯 TokenHub",
    category: "国内",
    protocol: "openai-chat",
    baseUrl: "https://tokenhub.tencentmaas.com",
    timeoutMs: 120000,
    reasoningDialect: "tencent-tokenhub-thinking",
    apiKeyPlaceholder: "sk-...",
    note: "腾讯 TokenHub OpenAI-compatible 入口，广州地域默认域名；新模型 Hy3 preview 支持 reasoning_effort。",
    deprecatedModelIds: ["hunyuan-turbos-latest", "hunyuan-t1-latest"],
    replacementModelIds: {
      "hunyuan-turbos-latest": "hy3-preview",
      "hunyuan-t1-latest": "hy3-preview",
    },
    models: [
      {
        displayName: "Hy3 Preview",
        modelId: "hy3-preview",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 256000,
        supportsReasoning: true,
        supportsVision: false,
      },
      {
        displayName: "DeepSeek V4 Pro",
        modelId: "deepseek-v4-pro",
        capabilities: ["chat", "reasoning", "vision", "tools"],
        contextLength: 1155072,
        supportsReasoning: true,
        supportsVision: true,
      },
      {
        displayName: "DeepSeek V4 Flash",
        modelId: "deepseek-v4-flash",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 1155072,
        supportsReasoning: true,
        supportsVision: false,
      },
    ],
  },
  {
    id: "modelscope",
    name: "ModelScope",
    category: "聚合",
    protocol: "openai-chat",
    baseUrl: "https://api-inference.modelscope.cn/v1",
    timeoutMs: 120000,
    reasoningDialect: "glm-thinking",
    apiKeyPlaceholder: "ms-...",
    note: "ModelScope OpenAI-compatible 推理入口，CC Switch Codex 预设默认使用 GLM-5.1。",
    models: [
      {
        displayName: "ZhipuAI / GLM-5.1",
        modelId: "ZhipuAI/GLM-5.1",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 200000,
        supportsReasoning: true,
        supportsVision: false,
      },
    ],
  },
  {
    id: "longcat",
    name: "LongCat",
    category: "国内",
    protocol: "openai-chat",
    baseUrl: "https://api.longcat.chat/openai/v1",
    timeoutMs: 120000,
    reasoningDialect: "none",
    apiKeyPlaceholder: "sk-...",
    note: "LongCat OpenAI-compatible 入口，默认按普通 Chat 模型处理，不额外注入推理参数。",
    models: [
      {
        displayName: "LongCat Flash Chat",
        modelId: "LongCat-Flash-Chat",
        capabilities: ["chat", "tools"],
        contextLength: 262144,
        supportsReasoning: false,
        supportsVision: false,
      },
    ],
  },
  {
    id: "xiaomi-mimo",
    name: "小米 MiMo",
    category: "国内",
    protocol: "openai-chat",
    baseUrl: "https://api.xiaomimimo.com/v1",
    timeoutMs: 120000,
    reasoningDialect: "glm-thinking",
    apiKeyPlaceholder: "sk-...",
    note: "小米 MiMo OpenAI-compatible 入口，推理开关按 thinking 方言映射。",
    models: [
      {
        displayName: "MiMo V2.5 Pro",
        modelId: "mimo-v2.5-pro",
        capabilities: ["chat", "reasoning", "tools"],
        contextLength: 1048576,
        supportsReasoning: true,
        supportsVision: false,
      },
    ],
  },
]

function stamp(prefix: string) {
  return `${prefix}-${Date.now()}-${crypto.randomUUID().slice(0, 8)}`
}

export function findProviderPreset(id: string) {
  return PROVIDER_PRESETS.find((preset) => preset.id === id)
}

export function createProviderPresetDraft(
  preset: ProviderPreset,
  existingProvider?: Provider,
): ProviderPresetDraft {
  const providerId = existingProvider?.id || stamp(`prov-${preset.id}`)
  const provider: Provider = {
    id: providerId,
    name: preset.name,
    protocol: preset.protocol,
    baseUrl: preset.baseUrl,
    apiKey: existingProvider?.apiKey || "",
    headers: (preset.headers || []).map((header) => ({
      id: stamp("h"),
      key: header.key,
      value: header.value,
    })),
    bodyOverride: "",
    timeoutMs: preset.timeoutMs,
    reasoningDialect: "auto",
    rawResponsesPassthrough: false,
    enabled: true,
    isDefault: existingProvider?.isDefault || false,
    health: existingProvider?.health || "healthy",
    healthMessage: existingProvider?.healthMessage,
  }

  return {
    provider,
    models: preset.models.map((model) => ({
      id: stamp(`m-${preset.id}`),
      providerId,
      displayName: model.displayName,
      modelId: model.modelId,
      capabilities: model.capabilities,
      contextLength: model.contextLength,
      supportsReasoning: model.supportsReasoning,
      reasoningDialect: model.reasoningDialect || preset.reasoningDialect,
      supportsVision: model.supportsVision,
      enabled: true,
    })),
  }
}
